### ISSUE TITLE
about default header files

### ISSUE THREAD

**Issue by legale** [tlwg/libdatrie#10] opened 2018-10-28 13:04 UTC
I'm trying to make an extension for php to work with your library. With the compiled version of the libdatrie from debian package i have successfully made these functions:
```
PHP_FUNCTION (trie_new);
PHP_FUNCTION(trie_state_new);
PHP_FUNCTION(trie_state_rewind);
PHP_FUNCTION(trie_store);
PHP_FUNCTION(trie_load);
PHP_FUNCTION(trie_save);
PHP_FUNCTION(trie_state_free);
PHP_FUNCTION(trie_state_walkable_chars);
PHP_FUNCTION(trie_state_walk);
PHP_FUNCTION(trie_state_rewind);
PHP_FUNCTION(trie_state_is_walkable);
PHP_FUNCTION(trie_state_is_single);
PHP_FUNCTION(trie_enumerate);
PHP_FUNCTION(trie_retrieve);
```
Now i'm trying to make PHP(tail_walk_char) which requires tail.h header. This header is not available in the package. Why?

**Comment by thep** [comment] 2018-11-20 08:07
`tail_walk_char()` is an internal function, not to be called directly.

**Comment by thep** [comment] 2018-11-23 08:01
Closing, as it's not a bug.

**Closed by thep** 2018-11-23 08:01 UTC
